### ISSUE TITLE
IA: Where to put a couple links?

### ISSUE THREAD

**Issue by aphelionz** [rs-ipfs/rustipfs.com#10]
We have, or will soon have, links now for:
- https://rs-ipfs.github.io/offchain-ipfs-manual/
- https://github.com/rs-ipfs/rust-ipfs/pull/420

How can we fit these onto the site in a cohesive way? Open to any and all suggestions.

**Comment by niklaslong** [comment]
There are two options that spring to mind: 
- next to the getting started button (obvious + nice group of three)
- below the getting started section (perhaps with a button for the section, making it obvious it's related but somewhat further reading) 

A reason for choosing the latter would be to add a sentence of context for each of these, it might not be immediately clear what these links are if we put them in buttons with `ipfs::offchain manual` and `http api tutorial` 🤔

**Comment by aphelionz** [comment]
The latter works for me. Could you take a stab at coding it up when you get a chance? It's an exceedingly simply site (bootstrap, etc)
